app/urls.py
from django.contrib import admin
from django.urls import path
from recipe import views

#--- ADDED THIS SECTION TO UPLOAD PHOTOS !!!! ---
from django.conf.urls.static import static
from django.conf import settings
#------------------------------------------------

#--- ADDED THIS SECTION FOR SMART SELECTS !!! ---
from django.urls import include
#------------------------------------------------

urlpatterns = [
    path('', views.recipe_view.as_view(), name='home'),
    path('admin/', admin.site.urls),
    #--- ADDED THIS SECTION FOR SMART SELECTS !!! ---
    path('chaining/', include('smart_selects.urls')),
    #------------------------------------------------
]

#--- ADDED THIS SECTION TO UPLOAD PHOTOS !!!! ---
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#------------------------------------------------

recipe/models.py
from django.db import models
from smart_selects.db_fields import ChainedForeignKey

class Minute(models.Model):
    minute = models.CharField(max_length=250)

    def __str__(self):
        return self.minute

class Hour(models.Model):
    hour = models.CharField(max_length=250)

    def __str__(self):
        return self.hour

class CookTime(models.Model):
    hour = models.ForeignKey(Hour, on_delete=models.CASCADE)
    minute = models.ForeignKey(Minute, on_delete=models.CASCADE)

    #pylint: disable=E1101
    def __str__(self):
        return self.hour.hour + " hr and " + self.minute.minute + " min"
    #pylint: enable=E1101

class ServingSize(models.Model):
    servingsize = models.CharField(max_length=250)

    def __str__(self):
        return self.servingsize

class Image(models.Model):
    image_title = models.CharField(max_length=250, default=None, blank=True, null=True)
    image = models.ImageField(upload_to='images/', default=None, blank=True, null=True)

    def __str__(self):
        return self.image_title

class Amount(models.Model):
    amount = models.CharField(max_length=250)

    def __str__(self):
        return self.amount

class Ingredient(models.Model):
    ingredient = models.CharField(max_length=250)
    link = models.CharField(max_length=250, default=None, blank=True, null=True)
    image = models.ImageField(upload_to='images/', default=None, blank=True, null=True)

    def __str__(self):
        return self.ingredient
    
class Unit(models.Model):
    unit = models.CharField(max_length=250)

    def __str__(self):
        return self.unit

class Category(models.Model):
    category = models.CharField(max_length=250)

    def __str__(self):
        return self.category

class Subcategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    subcategory = models.CharField(max_length=250, default="")

    def __str__(self):
        return self.subcategory

class RecipeName(models.Model):
    # description = models.TextField(default="")
    subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE)
    recipename = models.CharField(max_length=250, default="")

    def __str__(self):
        return self.recipename
    
class Recipe(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    subcategory = ChainedForeignKey(
        Subcategory,
        chained_field="category",
        chained_model_field="category",
        show_all=False,
        auto_choose=False,
        sort=True
    )
    recipename = ChainedForeignKey(
        RecipeName,
        chained_field="subcategory",
        chained_model_field="subcategory",
        show_all=False,
        auto_choose=False,
        sort=True
    )
    image = models.TextField(default=None, blank=True, null=True)
    description = models.TextField(default=None, blank=True, null=True)
    cooktime = models.ForeignKey(CookTime, on_delete=models.CASCADE, default=None, blank=True, null=True)
    servingsize =models.ForeignKey(ServingSize, on_delete=models.CASCADE, default=None, blank=True, null=True)

    def __str__(self):
        #pylint: disable=E1101
        return self.recipename.recipename
        #pylint: enable=E1101

class RecipeIngredient(models.Model):
    # image = models.ForeignKey(Image, on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    amount = models.ForeignKey(Amount, on_delete=models.CASCADE, default=None, blank=True, null=True)
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)

    def __str__(self):
        #pylint: disable=E1101
        return self.ingredient.ingredient
        #pylint: enable=E1101
    
class Direction(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    directions = models.TextField()

    def __str__(self):
        return self.directions
    
class Cookware(models.Model):
    cookware = models.CharField(max_length=250)
    link = models.TextField(default=None, blank=True, null=True)

    def __str__(self):
        return self.cookware
    
class RecipeCookware(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    cookware = models.ForeignKey(Cookware, on_delete=models.CASCADE)

    def __str__(self):
        #pylint: disable=E1101
        return self.cookware.cookware
        #pylint: enable=E1101

recipe/forms.py
from django import forms
from smart_selects.db_fields import ChainedForeignKey
from smart_selects.form_fields import ChainedModelChoiceField
from .models import Recipe, Direction, RecipeIngredient
from django.forms import widgets
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column, Div, Field

#pylint: disable=E1101

class RecipeForm(forms.ModelForm):
 
    class Meta:
        model = Recipe
        fields = ('category', 'subcategory', 'recipename')
        

    def __init__(self, *args, **kwargs):
        super(RecipeForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False

        # self.fields['category'].empty_label = 'SELECT CATEGORY'
        # self.fields['subcategory'].empty_label = 'Subcategory'
        # self.fields['recipename'].empty_label = 'Recipe'

recipe/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import Recipe, RecipeName, RecipeIngredient, Direction, Cookware, RecipeCookware, Image, CookTime, ServingSize, Ingredient
from django.views.generic import View
from .forms import RecipeForm
from django.forms import widgets

# Create your views here.
class recipe_view(View):    
    
    def get(self, request):
        form = RecipeForm()
        return render(request, "home.html", {'form': form})

    def post(self, request):
        form = RecipeForm(request.POST)
        if form.is_valid():
            tex = form.cleaned_data['recipename'].id
            recipes = Recipe.objects.filter(recipename_id=tex).values('id', 'category__category', 'subcategory__subcategory', 'recipename__recipename', 'image', 'description')
            ingredients = RecipeIngredient.objects.filter(recipe__in=recipes.values('id'))
            directions = Direction.objects.filter(recipe__in=recipes.values('id'))
            cookwares = RecipeCookware.objects.filter(recipe__in=recipes.values('id'))
            cooktimes = CookTime.objects.filter(recipe__in=recipes.values('id'))
            servingsizes = ServingSize.objects.filter(recipe__in=recipes.values('id'))
        args = {'form': form, 'ingredients': ingredients, 'servingsizes': servingsizes, 'cooktimes': cooktimes, 'recipes': recipes, 'directions': directions, 'cookwares': cookwares}
        return render(request, "home.html", args)

templates/home.html
{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>RECIPRY</title>
{% block headjavascript %}{{ form.media.js }}{% endblock %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
<link rel="alternate" type="application/json+oembed">

<script>
    $(document).ready(function() {
        $("select").on("change", function() {
            if($("select[name='category']").val() == "") { 
                $("select[name='category'] > option:first-child").text('Meal Type');
                $("select[name='subcategory']").prop('disabled', 'disabled');
                $("select[name='subcategory'] > option:first-child").text('Recipe Type');
                $("select[name='recipename']").prop('disabled', 'disabled');
                $("select[name='recipename'] > option:first-child").text('Pick Recipe');
            } else {
                $("select[name='subcategory']").removeAttr("disabled");
            }
        }).trigger('change');
        $("select[name='subcategory']").on("change", function() {
            if($("select[name='subcategory']").val() == "") { 
                $("select[name='recipename']").prop('disabled', 'disabled');
            } else {
                $("select[name='recipename']").removeAttr("disabled");
                $("select[name='category'] > option:first-child").text('Meal Type');
            }
        }).trigger('change');
    });
</script>
</head>
<body>
    {% block content %}
    <div class="container">
        <br/>
        <div class="row justify-content-center">
            <div class="col-12">
                <center><img src="https://www.recipry.com/media/images/recipry.png" alt="my image" height="100"></center>
            </div>
        </div>
        <br/>
        <form method="POST">
            <div class="form-row">
                {% csrf_token %}
                <div class="form-group custom-control col-md-3">         
                    {{form.category|add_class:"custom-select custom-select-lg"}}
                </div>
                <div class="form-group custom-control col-md-3">
                    <select name="subcategory" disabled class="custom-select custom-select-lg chained-fk" required="required" id="id_subcategory" data-chainfield="category" data-url="/chaining/filter/recipe/Subcategory/category/recipe/Recipe/subcategory" data-value="null" data-auto_choose="false" data-empty_label="Recipe Type">
                </select>
                </div>
                <div class="form-group custom-control col-md-3">
                    <select name="recipename" disabled class="custom-select custom-select-lg chained-fk" required="required" id="id_recipename" data-chainfield="subcategory" data-url="/chaining/filter/recipe/RecipeName/subcategory/recipe/Recipe/recipename" data-value="null" data-auto_choose="false" data-empty_label="Pick Recipe">
                </select>
                </div>
                <div class="form-group col-md-3">
                    <input type="submit" value="Submit" class="btn-lg btn-block" >
                </div>
            </div>
        </form>
        <div class="md">
        </div>
        {% if recipes %}
        <div class="row justify-content-center">
            <div class="col-12">
            <br>
            {% for recipe in recipes %}
                <h2>{{recipe.recipename__recipename}}</h2>
            {% endfor %}
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-12">
                <p>
                    {% autoescape off %}
                    {% for image in recipes %}
                        {{image.image}}
                    {% endfor %}
                    {% endautoescape %}
                </p>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-12">
                <p>
                    <u>DESCRIPTION:</u>
                    {% for recipe in recipes %}
                        {{recipe.description}}
                    {% endfor %}
                </p>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-12">
                    <p>
                        <u>COOKWARE:</u>
                        {% for cookware in cookwares %}
                            <a href="{{cookware.cookware.link}}" target="_blank">{{cookware.cookware}}</a>{%if not forloop.last%},{%endif%}
                        {% endfor %}
                        <br>
                    </p>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-12">
                <p>
                    <u>PREP & COOK TIME:</u>
                    {% for cooktime in cooktimes %}
                        {{cooktime.hour}} hr {{cooktime.minute}} min
                    {% endfor %}
                </p>
                <p>
                    <u>TOTAL SERVINGS:</u>
                    {% for servingsize in servingsizes %}
                        {{servingsize.servingsize}}
                    {% endfor %}
                </p>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-12">
                <ul class="nav nav-tabs nav-fill" id="myTab" role="tablist">
                    <li class="nav-item">
                    <a class="nav-link active" id="ingredients-tab" data-toggle="tab" href="#ingredients" role="tab" aria-controls="ingredients" aria-selected="true">INGREDIENTS</a>
                    </li>
                    <li class="nav-item ">
                    <a class="nav-link" id="directions-tab" data-toggle="tab" href="#directions" role="tab" aria-controls="directions" aria-selected="false">DIRECTIONS</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-12">   
                <div class="tab-content mt-4" id="myTabContent">
                    <div class="tab-pane fade show active" id="ingredients" role="tabpanel" aria-labelledby="ingredients-tab">
                        <table style="width: 100%">
                            {% for ingredient in ingredients %}
                            <tr>
                                <td>{{ingredient.amount}}</td>
                                <td>&nbsp;&nbsp;</td>
                                <td>{{ingredient.unit}}</td>
                                <td><a href="{{ingredient.ingredient.link}}" target="_blank">{{ingredient.ingredient}}</a></td>
                            </tr>
                            {% endfor %}
                        </table>
                    </div>
                    <div class="tab-pane fade" id="directions" role="tabpanel" aria-labelledby="directions-tab">
                        <table style="width: 100%">
                            {% for direction in directions %}
                                <tr>
                                    <td class="test">{{forloop.counter}}</td>
                                    <td>{{direction.directions|linebreaks}}</td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        <hr>
        <div class="row">
            <div class="col-12 footer">
                <p class="copy">© 2020 Recipry.com All Rights Reserved<br>
                Powered by <a class="copy" href="https://baffledjet.com" target="_blank">BAFFLEDJET.COM</a>
                </p>
            </div>
        </div>
    </div>
    {% endblock %}   
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>